services:

  discovery-server:
    build:
      context: ./discovery-server
      dockerfile: Dockerfile
    image: discovery-server:1.0
    ports:
      - "8761:8761"
    networks:
      - microservices-network

  product-service:
    build:
      context: ./product-service
      dockerfile: Dockerfile
    image: product-service:1.0
    environment:
      DB_URL: jdbc:mysql://mysql:3306/product_service
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/
    depends_on:
      mysql:
        condition: service_healthy
      discovery-server:
        condition: service_started
    networks:
      - microservices-network

  inventory-service:
    build:
      context: ./inventory-service
      dockerfile: Dockerfile
    image: inventory-service:1.0
    environment:
      DB_URL: jdbc:mysql://mysql:3306/inventory_service
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/
    depends_on:
      mysql:
        condition: service_healthy
      discovery-server:
        condition: service_started
    networks:
      - microservices-network

  order-service:
    build:
      context: ./order-service
      dockerfile: Dockerfile
    image: order-service:1.0
    environment:
      DB_URL: jdbc:mysql://mysql:3306/order_service
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/
    depends_on:
      mysql:
        condition: service_healthy
      discovery-server:
        condition: service_started
    networks:
      - microservices-network

  authentication-service:
    build:
      context: ./authentication-service
      dockerfile: Dockerfile
    image: authentication-service:1.0
    environment:
      DB_URL: jdbc:mysql://mysql:3306/auth_db
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION_MS: ${JWT_EXPIRATION_MS}
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/
      BREVO_API_KEY: ${BREVO_API_KEY}
      BREVO_SENDER_EMAIL: ${BREVO_SENDER_EMAIL}
      BREVO_SENDER_NAME: ${BREVO_SENDER_NAME}
    depends_on:
      mysql:
        condition: service_healthy
      discovery-server:
        condition: service_started
    networks:
      - microservices-network

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    image: api-gateway:1.0
    ports:
      - "8084:8084"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/
    depends_on:
      discovery-server:
        condition: service_started
    networks:
      - microservices-network

  mysql:
    image: mysql:8.3.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - microservices-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_PASSWORD}" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s


networks:
  microservices-network:
    driver: bridge

volumes:
  mysql-data: